portfolio/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('resume.urls',namespace="resume")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

resume/urls.py
from django.urls import path,re_path,include
from django.views.generic.base import TemplateView

from . import views

app_name = "resume"

urlpatterns = [
    path('',TemplateView.as_view(template_name="resume/index.html"), name="index"),
    path('resume/', TemplateView.as_view(template_name="resume/resume.html"), name="resume"),
    path('projects/',TemplateView.as_view(template_name="resume/project.html"), name="project"),
]

resume/models.py
from django.db import models

# Create your models here.

resume/views.py
from django.shortcuts import render

resume/templates/resume/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-111728662-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-111728662-1');
    </script>

    <meta charser="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta property="og:title" content="포트폴리오"/>
	<meta property="og:description" content="개발자로서의 이력서"/>
	<meta property="og:image" content="{% static 'img/portfolio.png' %}"/>

    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'css/font.css' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    {% block style %}{% endblock %}
</head>

<body>
    {% include 'resume/header.html' %}
    {% block content %}{% endblock %}

    <script src="{% static 'dist/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script src="{% static 'dist/js/bootstrap.min.js' %}"></script>
    <script defer src="{% static 'dist/js/fontawesome-all.js' %}"></script>
    {% block script %}{% endblock %}
</body>

</html>

resume/templates/resume/header.html
<div id="navi">
    <div id="menus">
        <a href="{% url 'resume:index' %}" id="home-btn">Home</a>
        <a href="{% url 'resume:project' %}" id="project-btn">Projects</a>
        <a href="https://jamiejang.blogspot.kr/" target="_blank">Blog</a>
    </div>
</div>

resume/templates/resume/index.html
{% extends 'resume/base.html' %}
{% load staticfiles %}

{% block title %}장지용{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/about.css' %}" />
{% endblock %}
{% block content %}

<div id="wrap">
    <div id="content">
        <div id="about">
            <h1 class='name'>장지용<span class='sub-name'>Django 개발자</span></h1>
            <p class='info-detail'>어제보다 더 나은 오늘을 모토로 개발을 하고 있습니다</p> 
            <a href="{% url 'resume:resume' %}" target="_blank" class="resume-link">
                <span class='fas fa-angle-double-right'></span> 이력서
            </a>
        </div>
    </div>
</div>

{% endblock %}

resume/templates/resume/project.html
{% extends 'resume/base.html' %}
{% load staticfiles %}

{% block title %}장지용{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/project.css' %}" />
{% endblock %}

{% block content %}

<div id="wrap">
    <div id="projects">
        <div class="each-project">
            <div class="project-info">
            </div>
            <div class="info">
                first project
            </div>
        </div>
        <div class="each-project">
            <div class="project-info">
            </div>
            <div class="info">
                second project
            </div>
        </div>
    </div>
</div>
    

{% endblock %}

resume/templates/resume/resume.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>이력서-장지용</title>
	<meta charset='utf-8'>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta property="og:title" content="이력서"/>
	<meta property="og:description" content="장지용의 이력서"/>

    <link rel="stylesheet" href="{% static 'dist/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/resume.css' %}" />
</head>
<body>
    <div class="resume-wrap">
        <div class="resume-box">
            <div class="personal">
                <div class="photo">
                    <img src="{% static 'img/profile.png' %}" align="middle" />
                </div>
                <div class="info">
                    <div class="position">
                        <div class="position-name">
                            백엔드(Django) 개발자
                        </div>
                    </div>
                    <div class="personal-info">
                        <div class="name">
                            <div class="real-name">
                                장지용
                            </div>
                        </div>
                        <div class="contact">
                            <div class="con">
                                <span class="fas fa-phone"></span>
                                &nbsp;&nbsp;010 9205 9417
                            </div>
                            <div class="con">
                                <span class="fab fa-google-plus-g"></span>&nbsp;
                                <a href="https://plus.google.com/116590924524324713794" target="_blank">
                                    wldyd9186@gmail.com</a>
                            </div>
                            <div class="con">
                                <span class="fab fa-github"></span>&nbsp;&nbsp;
                                <a href="https://github.com/JamieJang/" target="_blank">
                                    github.com/JamieJang</a>
                            </div>
                            <div class="con">
                                <span class="fas fa-home"></span>&nbsp;&nbsp;
                                <a href="http://www.jamiejang.me/" target="_blank">
                                    jamiejang.me</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="edu">
                <h2>학력</h2>
                <h4>대학교</h4>
                <p>서경대학교 (2010.03 ~ 2017.08) - 러시아어전공</p>
                <h4>학원</h4>
                <p>코리아 정보보안아카데미 ( 2016.12 ~ 2017.01 ) - 기초 파이썬과정</p>                
            </div>
            <div class="tech">
                <h2>기술</h2>
                <h4>가능함</h4>
                <p>Python, Django, HTML5/CSS3/JS, Jquery, Bootstrap, React, Git, AWS( EB, S3, RDS )</p>
                <h4>경험해봄</h4>
                <p>nginx,redis,postgresql,mysql, Vue.js</p>
                <h4>흥미있음</h4>
                <p>Docker</p>
            </div>
            <div class="project">
                <h2>개인 프로젝트 </h2>
                    <div class="each-project">
                        <h4 class="project-title">인스타그램 클론 프로젝트</h4>
                        <p class="project-term">2017.12.20 - 2018.1.7</p>
                        <div class="project-info">
                            <div class="info-title">
                                 사용된 기술:
                            </div>
                            <div class="info-detail">
                                 Django(백엔드), React,Redux(프론트엔드)
                            </div>
                        </div>
                        <div class="project-info">
                            <div class="info-title">
                             목표:
                            </div>
                            <div class="info-detail">
                                 실제 서비스 되는 사이트를 클론 코딩 함으로써 가지고 있는 기술들을
                                실무에서 어떻게 사용해야 할 지 알아가는 것
                            </div>
                        </div>
                        <div class="project-info">
                            <div class="info-title">
                                결과:
                            </div>
                            <div class="info-detail">
                                Django를 사용해서 REST API 서버를 구성하는 방법과, React/Redux를 사용하여 SPA(Single Page Application)를
                                만드는 방법을 익힘
                            </div>
                        </div>
                        <div class="project-image">
                            <img src="{% static 'img/jamiegram1.png' %}" alt="jamiegram" />
                            <img src="{% static 'img/jamiegram2.png' %}" alt="jamiegram" />
                            <img src="{% static 'img/jamiegram3.png' %}" alt="jamiegram" />
                        </div>
                        
                    </div>
                </h2>
            </div>
            <div class="cv">
                <h2>자기소개</h2>
                <p style="line-height: 2"> 백엔드 개발자, 나아가 풀스택 개발자가 되려는 신입 프로그래머입니다.
                    프로그래밍에 흥미를 느끼게 된 이유는 컴퓨터 하나만으로도 이 세상 많은 사람에게 제 생각을 보여 줄 수 있다는 것이었습니다.
                    대다수의 사람처럼 전공으로 배운 것은 아니지만, 그 누구보다 큰 열정을 가지고 개발자의 길로 뛰어들었습니다.
                    대부분의 기술을 독학으로 배웠고, 그로 인해서 새로운 기술에 대한 알맞은 정보를 찾는 방법과 빠른 습득능력을 키우게 되었습니다. 
                    빠르고 편리한 웹 서비스를 만드는 것을 지향하고 있어서, 데이터 처리방법에 대해 많은 관심이 있고, 
                    많은 웹 사이트들을 돌아다니며 새로운 기술을 찾아보는 것을 좋아합니다. 그리고 그 기술이 어떤 방식으로 이루어졌는지 이해하고 직접 실습해 보면서 이해합니다.
                    프로그래밍에 대한 다양한 지식을 가지는 것도 중요하지만, 기초적인 프로그래밍 지식과 함께 수많은 정보 가운데에서 알맞은 기술을 생각하고 찾아내서 
                    빠르게 서비스에 적용하는 점이 현재 개발자에게 있어 더 중요한 점이라고 생각합니다. 저는 혼자서 기술들을 배우면서 그러한 점을 많이 단련시켰습니다. 
                    어떻게 검색하고 어떻게 적용하는지 잘 알고 있습니다. 이러한 점을 저의 장점으로 내세워 실무에서 개발자의 역할을 해 낼 수 있다고 자신합니다.
                    </p>
            </div>
        </div>
    </div>

    <script src="{% static 'dist/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
    <script defer src="{% static 'dist/js/fontawesome-all.js' %}"></script>

    <script>
        $(document).ready(function(){
            var w = $(".personal").height()*0.85;
            $(".photo img").height(w);
        });
        $(document).ready(function(){
            var w = $(window).width();
            if(w <= 768){
                $(".photo").css("display","none");
            }else{
                $(".photo").css("display","initial");
            }
        })
        $(window).resize(function(){
            var w = $(window).width();
            if(w <= 768){
                $(".photo").css("display","none");
            }else{
                $(".photo").css("display","initial");
            }
        });
    </script>

<body>
</html>